package festivalaplikacija.klijent.ki.forma.izvodjac;

import festivalaplikacija.klijent.ki.forma.izvodjac.kontroler.DodajIzvodjacaFormaKontroler;
import javax.swing.JOptionPane;

/**
 *
 * @author Dušan Kalejski dramski pedagog
 */
public class DodajIzvodjacaForma extends javax.swing.JDialog {

    /**
     * Creates new form DodajIzvodjacaForma1
     */
    public DodajIzvodjacaForma(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUnosIzvodjacNaziv = new javax.swing.JTextField();
        lblUnosIzvodjacNaziv = new javax.swing.JLabel();
        lblUnosIzvodjacKontaktOsoba = new javax.swing.JLabel();
        txtUnosIzvodjacKontaktOsoba = new javax.swing.JTextField();
        txtUnosIzvodjacEmail = new javax.swing.JTextField();
        lblUnosIzvodjacEmail = new javax.swing.JLabel();
        lblUnosIzvodjacTelefon = new javax.swing.JLabel();
        txtUnosIzvodjacTelefon = new javax.swing.JTextField();
        lblUnosIzvodjacMesto = new javax.swing.JLabel();
        comboBoxUnosIzvodjacMesto = new javax.swing.JComboBox<>();
        btnUnosIzvodjacDodajMesto = new javax.swing.JButton();
        btnUnosIzvodjacDodaj = new javax.swing.JButton();
        btnUnosIzvodjacIzadji = new javax.swing.JButton();
        lblUnosIzvodjacGreska = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj izvodjaca");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        txtUnosIzvodjacNaziv.setBackground(new java.awt.Color(204, 224, 239));
        txtUnosIzvodjacNaziv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUnosIzvodjacNaziv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUnosIzvodjacNaziv.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        lblUnosIzvodjacNaziv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnosIzvodjacNaziv.setText("Naziv:");

        lblUnosIzvodjacKontaktOsoba.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnosIzvodjacKontaktOsoba.setText("Kontakt osoba:");

        txtUnosIzvodjacKontaktOsoba.setBackground(new java.awt.Color(204, 224, 239));
        txtUnosIzvodjacKontaktOsoba.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUnosIzvodjacKontaktOsoba.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtUnosIzvodjacEmail.setBackground(new java.awt.Color(204, 224, 239));
        txtUnosIzvodjacEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUnosIzvodjacEmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUnosIzvodjacEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnosIzvodjacEmail.setText("email:");

        lblUnosIzvodjacTelefon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnosIzvodjacTelefon.setText("Telefon:");

        txtUnosIzvodjacTelefon.setBackground(new java.awt.Color(204, 224, 239));
        txtUnosIzvodjacTelefon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUnosIzvodjacTelefon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblUnosIzvodjacMesto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnosIzvodjacMesto.setText("Mesto:");

        comboBoxUnosIzvodjacMesto.setBackground(new java.awt.Color(204, 224, 239));
        comboBoxUnosIzvodjacMesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        comboBoxUnosIzvodjacMesto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnUnosIzvodjacDodajMesto.setBackground(new java.awt.Color(175, 221, 206));
        btnUnosIzvodjacDodajMesto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUnosIzvodjacDodajMesto.setText("Dodaj mesto");
        btnUnosIzvodjacDodajMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosIzvodjacDodajMestoActionPerformed(evt);
            }
        });

        btnUnosIzvodjacDodaj.setBackground(new java.awt.Color(235, 225, 145));
        btnUnosIzvodjacDodaj.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUnosIzvodjacDodaj.setText("Dodaj");
        btnUnosIzvodjacDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosIzvodjacDodajActionPerformed(evt);
            }
        });

        btnUnosIzvodjacIzadji.setBackground(new java.awt.Color(236, 197, 181));
        btnUnosIzvodjacIzadji.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUnosIzvodjacIzadji.setText("Izadji");
        btnUnosIzvodjacIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnosIzvodjacIzadjiActionPerformed(evt);
            }
        });

        lblUnosIzvodjacGreska.setForeground(new java.awt.Color(255, 0, 51));
        lblUnosIzvodjacGreska.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUnosIzvodjacKontaktOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnosIzvodjacNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnosIzvodjacEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnosIzvodjacTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUnosIzvodjacEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnosIzvodjacNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnosIzvodjacKontaktOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnosIzvodjacTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblUnosIzvodjacMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(comboBoxUnosIzvodjacMesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(btnUnosIzvodjacDodajMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))))
                    .addComponent(lblUnosIzvodjacGreska, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUnosIzvodjacIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUnosIzvodjacDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnosIzvodjacNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnosIzvodjacNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnosIzvodjacMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnosIzvodjacKontaktOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnosIzvodjacKontaktOsoba, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxUnosIzvodjacMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnosIzvodjacEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnosIzvodjacEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnosIzvodjacDodajMesto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnosIzvodjacTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUnosIzvodjacTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUnosIzvodjacGreska)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnosIzvodjacDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUnosIzvodjacIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnosIzvodjacDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosIzvodjacDodajActionPerformed
        DodajIzvodjacaFormaKontroler.add(lblUnosIzvodjacGreska, txtUnosIzvodjacNaziv, txtUnosIzvodjacKontaktOsoba, txtUnosIzvodjacEmail, txtUnosIzvodjacTelefon, comboBoxUnosIzvodjacMesto, this);
    }//GEN-LAST:event_btnUnosIzvodjacDodajActionPerformed

    private void btnUnosIzvodjacDodajMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosIzvodjacDodajMestoActionPerformed
        try {
            DodajIzvodjacaFormaKontroler.dodajMesto(txtUnosIzvodjacNaziv, txtUnosIzvodjacKontaktOsoba, txtUnosIzvodjacTelefon, txtUnosIzvodjacEmail);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Konekcija sa serverom je prekinuta. Vaša sesija će biti zatvorena", "ERROR", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_btnUnosIzvodjacDodajMestoActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            pripremiFormu();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Konekcija sa serverom je prekinuta. Vaša sesija će biti zatvorena", "ERROR", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnUnosIzvodjacIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnosIzvodjacIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_btnUnosIzvodjacIzadjiActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        DodajIzvodjacaFormaKontroler.formWindowGainedFocus(txtUnosIzvodjacNaziv, txtUnosIzvodjacKontaktOsoba, txtUnosIzvodjacEmail, txtUnosIzvodjacTelefon);
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        DodajIzvodjacaFormaKontroler.formWindowLostFocus(txtUnosIzvodjacNaziv, txtUnosIzvodjacKontaktOsoba, txtUnosIzvodjacTelefon, txtUnosIzvodjacEmail);
    }//GEN-LAST:event_formWindowLostFocus


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUnosIzvodjacDodaj;
    private javax.swing.JButton btnUnosIzvodjacDodajMesto;
    private javax.swing.JButton btnUnosIzvodjacIzadji;
    private javax.swing.JComboBox<Object> comboBoxUnosIzvodjacMesto;
    private javax.swing.JLabel lblUnosIzvodjacEmail;
    private javax.swing.JLabel lblUnosIzvodjacGreska;
    private javax.swing.JLabel lblUnosIzvodjacKontaktOsoba;
    private javax.swing.JLabel lblUnosIzvodjacMesto;
    private javax.swing.JLabel lblUnosIzvodjacNaziv;
    private javax.swing.JLabel lblUnosIzvodjacTelefon;
    private javax.swing.JTextField txtUnosIzvodjacEmail;
    private javax.swing.JTextField txtUnosIzvodjacKontaktOsoba;
    private javax.swing.JTextField txtUnosIzvodjacNaziv;
    private javax.swing.JTextField txtUnosIzvodjacTelefon;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() throws Exception {
        DodajIzvodjacaFormaKontroler.prepareForm(lblUnosIzvodjacGreska, txtUnosIzvodjacNaziv, txtUnosIzvodjacKontaktOsoba, txtUnosIzvodjacEmail, txtUnosIzvodjacTelefon, comboBoxUnosIzvodjacMesto);
        popuniComboBox();
    }

    private void popuniComboBox() throws Exception {
        DodajIzvodjacaFormaKontroler.fillComboBox(comboBoxUnosIzvodjacMesto, lblUnosIzvodjacGreska);

    }
}
