package festivalaplikacija.klijent.ki.forma.izvodjac;

import festivalaplikacija.klijent.ki.forma.izvodjac.kontroler.PrikaziIzvodjacaFormaKontroler;

/**
 *
 * @author Dušan Kalejski dramski pedagog
 */
public class PrikaziIzvodjacaForma extends javax.swing.JDialog {

    /**
     * Creates new form PrikaziIzvodjacaForma
     */
    public PrikaziIzvodjacaForma(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        PrikaziIzvodjacaFormaKontroler.pripremiFormu(tblPrikaziIzvodjaca, lblPrikaziIzvodjaceGreska, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrikaziIzvodjaca = new javax.swing.JTable();
        btnPrikaziSvePodatke = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextAreaPrikaziSvePodatke = new javax.swing.JTextArea();
        btnIzadji = new javax.swing.JButton();
        lblPrikaziIzvodjaceGreska = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Spisak izvodjaca:");

        tblPrikaziIzvodjaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrikaziIzvodjaca);

        btnPrikaziSvePodatke.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrikaziSvePodatke.setText("Prikazi sve podatke");
        btnPrikaziSvePodatke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziSvePodatkeActionPerformed(evt);
            }
        });

        TextAreaPrikaziSvePodatke.setBackground(new java.awt.Color(228, 226, 226));
        TextAreaPrikaziSvePodatke.setColumns(20);
        TextAreaPrikaziSvePodatke.setRows(5);
        jScrollPane2.setViewportView(TextAreaPrikaziSvePodatke);

        btnIzadji.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        lblPrikaziIzvodjaceGreska.setForeground(new java.awt.Color(204, 0, 51));
        lblPrikaziIzvodjaceGreska.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrikaziIzvodjaceGreska, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPrikaziSvePodatke)
                            .addComponent(btnIzadji))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblPrikaziIzvodjaceGreska)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrikaziSvePodatke, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzadji))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrikaziSvePodatkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziSvePodatkeActionPerformed
        PrikaziIzvodjacaFormaKontroler.prikaziSvePodatke(tblPrikaziIzvodjaca, lblPrikaziIzvodjaceGreska, TextAreaPrikaziSvePodatke);
    }//GEN-LAST:event_btnPrikaziSvePodatkeActionPerformed

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextAreaPrikaziSvePodatke;
    private javax.swing.JButton btnIzadji;
    private javax.swing.JButton btnPrikaziSvePodatke;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPrikaziIzvodjaceGreska;
    private javax.swing.JTable tblPrikaziIzvodjaca;
    // End of variables declaration//GEN-END:variables

    

   
}
