package festivalaplikacija.klijent.ki.forma.drzava;

import festivalaplikacija.zajednicki.domen.Drzava;
import festivalaplikacija.klijent.ki.forma.drzava.kontroler.AzurirajDrzavuFormaKontroler;

/**
 *
 * @author Dušan Kalejski dramski pedagog
 */
public class AzurirajDrzavuForma extends javax.swing.JDialog {

    private final Drzava drzava;

    /**
     * Creates new form DodajDrzavuForma
     */
    public AzurirajDrzavuForma(java.awt.Frame parent, boolean modal, Drzava drzava) {
        super(parent, modal);
        this.drzava = drzava;
        initComponents();
        lblGreskaAzurirajDrzavu.setText("");
        setLocationRelativeTo(null);
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaziv = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        lblSkraceniNaziv = new javax.swing.JLabel();
        txtSkraceniNaziv = new javax.swing.JTextField();
        lblGreskaAzurirajDrzavu = new javax.swing.JLabel();
        btnAzurirajDrzavu = new javax.swing.JButton();
        btnIzadji = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj novu drzavu");
        setBackground(new java.awt.Color(0, 0, 0));

        lblNaziv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNaziv.setText("Naziv:");

        lblSkraceniNaziv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSkraceniNaziv.setText("Skraceni naziv:");

        lblGreskaAzurirajDrzavu.setBackground(new java.awt.Color(255, 255, 255));
        lblGreskaAzurirajDrzavu.setForeground(new java.awt.Color(255, 0, 51));
        lblGreskaAzurirajDrzavu.setText("jLabel2");

        btnAzurirajDrzavu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAzurirajDrzavu.setText("Azuriraj");
        btnAzurirajDrzavu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzurirajDrzavuActionPerformed(evt);
            }
        });

        btnIzadji.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNaziv))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblSkraceniNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSkraceniNaziv))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 333, Short.MAX_VALUE)
                                        .addComponent(btnAzurirajDrzavu, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGreskaAzurirajDrzavu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSkraceniNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSkraceniNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGreskaAzurirajDrzavu)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAzurirajDrzavu)
                    .addComponent(btnIzadji))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    private void btnAzurirajDrzavuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzurirajDrzavuActionPerformed
        AzurirajDrzavuFormaKontroler.update(txtNaziv, txtSkraceniNaziv, this, drzava, lblGreskaAzurirajDrzavu);

    }//GEN-LAST:event_btnAzurirajDrzavuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzurirajDrzavu;
    private javax.swing.JButton btnIzadji;
    private javax.swing.JLabel lblGreskaAzurirajDrzavu;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblSkraceniNaziv;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtSkraceniNaziv;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        txtNaziv.setText(drzava.getNaziv());
        txtSkraceniNaziv.setText(drzava.getSkraceniNaziv());
    }

}
