package festivalaplikacija.klijent.ki.forma.drzava;

import festivalaplikacija.klijent.ki.forma.drzava.kontroler.IzmeniDrzavuFormaKontroler;
import festivalaplikacija.klijent.ki.forma.drzava.kontroler.PrikaziDrzavuFormaKontroler;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dušan Kalejski dramski pedagog
 */
public class IzmeniDrzavuForma extends javax.swing.JDialog {

    /**
     * Creates new form IzmeniDrzavuForma
     */
    public IzmeniDrzavuForma(java.awt.Frame parent, boolean modal) throws IOException, Exception {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        pripremiFormu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrzavaPrikaz = new javax.swing.JTable();
        lblGreska = new javax.swing.JLabel();
        btnIzadji = new javax.swing.JButton();
        btnIzmeniDrzavu = new javax.swing.JButton();
        btnObrisiDrzavu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tblDrzavaPrikaz.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblDrzavaPrikaz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDrzavaPrikaz);

        lblGreska.setForeground(new java.awt.Color(255, 0, 51));
        lblGreska.setText("jLabel1");

        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        btnIzmeniDrzavu.setText("Izmeni");
        btnIzmeniDrzavu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniDrzavuActionPerformed(evt);
            }
        });

        btnObrisiDrzavu.setText("Obrisi");
        btnObrisiDrzavu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiDrzavuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblGreska, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeniDrzavu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnObrisiDrzavu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGreska)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzadji)
                    .addComponent(btnIzmeniDrzavu)
                    .addComponent(btnObrisiDrzavu))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiDrzavuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiDrzavuActionPerformed
        IzmeniDrzavuFormaKontroler.delete(tblDrzavaPrikaz, lblGreska, this);
    }//GEN-LAST:event_btnObrisiDrzavuActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            PrikaziDrzavuFormaKontroler.pripremiFormu(tblDrzavaPrikaz);
        } catch (Exception ex) {
            Logger.getLogger(IzmeniDrzavuForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    private void btnIzmeniDrzavuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniDrzavuActionPerformed
        IzmeniDrzavuFormaKontroler.OpenUpdateWindow(tblDrzavaPrikaz, lblGreska);
    }//GEN-LAST:event_btnIzmeniDrzavuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzadji;
    private javax.swing.JButton btnIzmeniDrzavu;
    private javax.swing.JButton btnObrisiDrzavu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGreska;
    private javax.swing.JTable tblDrzavaPrikaz;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() throws IOException, Exception {
        IzmeniDrzavuFormaKontroler.postaviModelTabele(tblDrzavaPrikaz);
        lblGreska.setText("");
    }

}
