package festivalaplikacija.klijent.ki.komponenta.program.panel;

import festivalaplikacija.klijent.ki.forma.program.ProgramForma;
import festivalaplikacija.klijent.operacija.ZahtevKlijent;
import festivalaplikacija.klijent.validacija.Validacija;
import festivalaplikacija.zajednicki.domen.DanProgram;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Dušan Kalejski dramski pedagog
 */
public class MojPanelDodajDan extends javax.swing.JPanel {

    ProgramForma forma;
    JDialog dialog;

    /**
     * Creates new form MojPanelDodajDan
     */
    public MojPanelDodajDan(JDialog dialog, ProgramForma forma) {
        initComponents();
        txtNazivDan.setText("");
        this.forma = forma;
        this.dialog = dialog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDodajDan = new javax.swing.JPanel();
        lblNazivDan = new javax.swing.JLabel();
        txtNazivDan = new javax.swing.JTextField();
        lblDatumDan = new javax.swing.JLabel();
        dateDan = new com.toedter.calendar.JDateChooser();
        btnOdustaniOdDodavanja = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();

        pnlDodajDan.setBackground(new java.awt.Color(142, 164, 227));

        lblNazivDan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNazivDan.setText("Naziv:");

        txtNazivDan.setText("jTextField1");

        lblDatumDan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDatumDan.setText("Datum:");

        btnOdustaniOdDodavanja.setText("Vrati se");
        btnOdustaniOdDodavanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdustaniOdDodavanjaActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDodajDanLayout = new javax.swing.GroupLayout(pnlDodajDan);
        pnlDodajDan.setLayout(pnlDodajDanLayout);
        pnlDodajDanLayout.setHorizontalGroup(
            pnlDodajDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDodajDanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNazivDan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtNazivDan, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDatumDan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateDan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnOdustaniOdDodavanja, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDodajDanLayout.setVerticalGroup(
            pnlDodajDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDodajDanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDodajDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDodajDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNazivDan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNazivDan)
                        .addComponent(lblDatumDan))
                    .addGroup(pnlDodajDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDodaj)
                        .addComponent(btnOdustaniOdDodavanja))
                    .addComponent(dateDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDodajDan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDodajDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdustaniOdDodavanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdustaniOdDodavanjaActionPerformed
        this.setVisible(false);
        dialog.dispose();
    }//GEN-LAST:event_btnOdustaniOdDodavanjaActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        String naziv = txtNazivDan.getText();
        Date datum = dateDan.getDate();
        try {
            Validacija.getInstance().isEmpty(naziv);
            DanProgram danProgram = new DanProgram(naziv, datum);
            ZahtevKlijent.addDanProgram(danProgram);
                this.setVisible(false);
                dialog.dispose();
                forma.setNoviDan(danProgram);
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena");
        }
    }//GEN-LAST:event_btnDodajActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnOdustaniOdDodavanja;
    private com.toedter.calendar.JDateChooser dateDan;
    private javax.swing.JLabel lblDatumDan;
    private javax.swing.JLabel lblNazivDan;
    private javax.swing.JPanel pnlDodajDan;
    private javax.swing.JTextField txtNazivDan;
    // End of variables declaration//GEN-END:variables
}
