package festivalaplikacija.klijent.ki.forma.mesto;

import festivalaplikacija.zajednicki.domen.Mesto;
import festivalaplikacija.klijent.ki.forma.mesto.kontroler.AzurirajMestoFormaKontroler;

/**
 *
 * @author Dušan Kalejski dramski pedagog
 */
public class AzurirajMestoForma extends javax.swing.JDialog {

    private final Mesto mesto;

    /**
     * Creates new form DodajDrzavuForma
     *
     *
     */
    public AzurirajMestoForma(java.awt.Frame parent, boolean modal, Mesto mesto) {
        super(parent, modal);
        this.mesto = mesto;
        initComponents();
        lblGreskaAzurirajMesto.setText("");
        setLocationRelativeTo(null);
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNaziv = new javax.swing.JLabel();
        txtNaziv = new javax.swing.JTextField();
        lblPtt = new javax.swing.JLabel();
        txtPtt = new javax.swing.JTextField();
        lblGreskaAzurirajMesto = new javax.swing.JLabel();
        btnAzurirajMesto = new javax.swing.JButton();
        btnIzadji = new javax.swing.JButton();
        lblDrzava = new javax.swing.JLabel();
        txtDrzava = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj novu drzavu");
        setBackground(new java.awt.Color(0, 0, 0));

        lblNaziv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNaziv.setText("Naziv:");

        lblPtt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPtt.setText("PTT:");

        lblGreskaAzurirajMesto.setBackground(new java.awt.Color(255, 255, 255));
        lblGreskaAzurirajMesto.setForeground(new java.awt.Color(255, 0, 51));
        lblGreskaAzurirajMesto.setText("jLabel2");

        btnAzurirajMesto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAzurirajMesto.setText("Azuriraj");
        btnAzurirajMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAzurirajMestoActionPerformed(evt);
            }
        });

        btnIzadji.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        lblDrzava.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDrzava.setText("Drzava:");

        txtDrzava.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGreskaAzurirajMesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDrzava))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNaziv, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPtt, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPtt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAzurirajMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPtt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPtt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGreskaAzurirajMesto)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIzadji)
                    .addComponent(btnAzurirajMesto))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    private void btnAzurirajMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAzurirajMestoActionPerformed
        AzurirajMestoFormaKontroler.update(txtNaziv, txtPtt, mesto, this, lblGreskaAzurirajMesto);
    }//GEN-LAST:event_btnAzurirajMestoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAzurirajMesto;
    private javax.swing.JButton btnIzadji;
    private javax.swing.JLabel lblDrzava;
    private javax.swing.JLabel lblGreskaAzurirajMesto;
    private javax.swing.JLabel lblNaziv;
    private javax.swing.JLabel lblPtt;
    private javax.swing.JTextField txtDrzava;
    private javax.swing.JTextField txtNaziv;
    private javax.swing.JTextField txtPtt;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() {
        txtNaziv.setText(mesto.getNaziv());
        txtPtt.setText(String.valueOf(mesto.getPtt()));
        txtDrzava.setText(mesto.getDrzava().getNaziv()+", "+mesto.getDrzava().getSkraceniNaziv());
    }

}
