package festivalaplikacija.klijent.ki.forma.mesto;

import festivalaplikacija.klijent.ki.forma.drzava.DodajDrzavuForma;
import festivalaplikacija.klijent.ki.forma.mesto.kontroler.DodajMestoFormaKontroler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dušan Kalejski dramski pedagog
 */
public class DodajMestoForma extends javax.swing.JDialog {

    /**
     * Creates new form DodajMesto
     */
    public DodajMestoForma(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        pripremiFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUnosMestoNaziv = new javax.swing.JLabel();
        lblUnosMestoPTT = new javax.swing.JLabel();
        lblUnosMestoDrzava = new javax.swing.JLabel();
        comboBoxUnosMestoDrzava = new javax.swing.JComboBox<>();
        txtUnosMestoNaziv = new javax.swing.JTextField();
        txtUnosMestoPTT = new javax.swing.JTextField();
        btnDodajDrzavu = new javax.swing.JButton();
        btnDodajMesto = new javax.swing.JButton();
        btnIzadji = new javax.swing.JButton();
        lblGreskaDodajMeto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos novog mesta:");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lblUnosMestoNaziv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnosMestoNaziv.setText("Naziv:");

        lblUnosMestoPTT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnosMestoPTT.setText("PTT:");

        lblUnosMestoDrzava.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUnosMestoDrzava.setText("Drzava:");

        comboBoxUnosMestoDrzava.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtUnosMestoNaziv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtUnosMestoPTT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnDodajDrzavu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDodajDrzavu.setText("Dodaj drzavu");
        btnDodajDrzavu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajDrzavuActionPerformed(evt);
            }
        });

        btnDodajMesto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDodajMesto.setText("Dodaj");
        btnDodajMesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajMestoActionPerformed(evt);
            }
        });

        btnIzadji.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIzadji.setText("Izadji");
        btnIzadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzadjiActionPerformed(evt);
            }
        });

        lblGreskaDodajMeto.setForeground(new java.awt.Color(255, 0, 51));
        lblGreskaDodajMeto.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblGreskaDodajMeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUnosMestoNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblUnosMestoDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtUnosMestoNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                        .addComponent(lblUnosMestoPTT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(comboBoxUnosMestoDrzava, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUnosMestoPTT)
                            .addComponent(btnDodajDrzavu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDodajMesto, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUnosMestoPTT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUnosMestoPTT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblUnosMestoNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUnosMestoNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnosMestoDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxUnosMestoDrzava, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajDrzavu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGreskaDodajMeto)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodajMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzadji, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIzadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzadjiActionPerformed
        dispose();
    }//GEN-LAST:event_btnIzadjiActionPerformed

    private void btnDodajMestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajMestoActionPerformed
        DodajMestoFormaKontroler.add(lblGreskaDodajMeto, txtUnosMestoNaziv, txtUnosMestoPTT, comboBoxUnosMestoDrzava, this);
    }//GEN-LAST:event_btnDodajMestoActionPerformed

    private void btnDodajDrzavuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajDrzavuActionPerformed
        DodajMestoFormaKontroler.cuvajPrivremenePodatkeIzForme(txtUnosMestoNaziv, txtUnosMestoPTT);
        DodajDrzavuForma dodajDrzavuForma = new DodajDrzavuForma(null, true);
        dodajDrzavuForma.setVisible(true);
    }//GEN-LAST:event_btnDodajDrzavuActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            pripremiFormu();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Konekcija sa serverom je prekinuta. Vaša sesija će biti zatvorena", "ERROR", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        DodajMestoFormaKontroler.formWindowGainedFocus(txtUnosMestoNaziv, txtUnosMestoPTT);
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        DodajMestoFormaKontroler.cuvajPrivremenePodatkeIzForme(txtUnosMestoNaziv, txtUnosMestoPTT);
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajDrzavu;
    private javax.swing.JButton btnDodajMesto;
    private javax.swing.JButton btnIzadji;
    private javax.swing.JComboBox<String> comboBoxUnosMestoDrzava;
    private javax.swing.JLabel lblGreskaDodajMeto;
    private javax.swing.JLabel lblUnosMestoDrzava;
    private javax.swing.JLabel lblUnosMestoNaziv;
    private javax.swing.JLabel lblUnosMestoPTT;
    private javax.swing.JTextField txtUnosMestoNaziv;
    private javax.swing.JTextField txtUnosMestoPTT;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() throws Exception {
        lblGreskaDodajMeto.setText("");
        txtUnosMestoNaziv.setText("");
        txtUnosMestoPTT.setText("");
        DodajMestoFormaKontroler.fillComboBox(comboBoxUnosMestoDrzava, lblGreskaDodajMeto);

    }

}
