package festivalaplikacija.klijent.ki.forma.program;

import festivalaplikacija.klijent.ki.forma.program.kontroler.ProgramFormaKontroler;
import static festivalaplikacija.klijent.ki.forma.program.kontroler.ProgramFormaKontroler.pripremiFormu;
import festivalaplikacija.klijent.ki.komponenta.program.panel.MojPanelDodajDan;
import festivalaplikacija.zajednicki.domen.DanProgram;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dušan Kalejski dramski pedagog
 */
public class ProgramForma extends javax.swing.JDialog {

    private DanProgram noviDan = null;
    private final List<String> daniZaBrisanje;

    /**
     * Creates new form ProgramForma
     */
    public ProgramForma(java.awt.Frame parent, boolean modal) throws Exception {
        super(parent, modal);
        initComponents();
        daniZaBrisanje = new ArrayList<>();
        this.setSize(Integer.MAX_VALUE, Integer.MAX_VALUE);
        pnlPrikazDana.setLayout(new FlowLayout());
        pnlObrisiDan.setLayout(new FlowLayout());
        pripremiFormu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrikazDana = new javax.swing.JPanel();
        btnDodajDan = new javax.swing.JButton();
        btnObrisiDan = new javax.swing.JButton();
        pnlObrisiDan = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout pnlPrikazDanaLayout = new javax.swing.GroupLayout(pnlPrikazDana);
        pnlPrikazDana.setLayout(pnlPrikazDanaLayout);
        pnlPrikazDanaLayout.setHorizontalGroup(
            pnlPrikazDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        pnlPrikazDanaLayout.setVerticalGroup(
            pnlPrikazDanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 114, Short.MAX_VALUE)
        );

        btnDodajDan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDodajDan.setText("Dodaj dan");
        btnDodajDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajDanActionPerformed(evt);
            }
        });

        btnObrisiDan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnObrisiDan.setText("Obrisi Dan");
        btnObrisiDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiDanActionPerformed(evt);
            }
        });

        pnlObrisiDan.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlObrisiDanLayout = new javax.swing.GroupLayout(pnlObrisiDan);
        pnlObrisiDan.setLayout(pnlObrisiDanLayout);
        pnlObrisiDanLayout.setHorizontalGroup(
            pnlObrisiDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        pnlObrisiDanLayout.setVerticalGroup(
            pnlObrisiDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrikazDana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnDodajDan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnObrisiDan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlObrisiDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlObrisiDan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnObrisiDan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodajDan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(pnlPrikazDana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDodajDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajDanActionPerformed
        try {
            JDialog dialog = new JDialog(this, true);
            JPanel panel = new MojPanelDodajDan(dialog, this);
            ProgramFormaKontroler.dodajDan(dialog, panel);
            this.setSize(Integer.MAX_VALUE, (Integer.MAX_VALUE - 1));
            this.setSize(Integer.MAX_VALUE, Integer.MAX_VALUE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Konekcija sa serverom je prekinuta. Vaša sesija će biti zatvorena", "ERROR", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }


    }//GEN-LAST:event_btnDodajDanActionPerformed

    private void btnObrisiDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiDanActionPerformed
        ProgramFormaKontroler.obrisiDan(daniZaBrisanje, this, pnlPrikazDana, btnDodajDan, pnlObrisiDan);
        this.setSize(Integer.MAX_VALUE, (Integer.MAX_VALUE - 1));
        this.setSize(Integer.MAX_VALUE, Integer.MAX_VALUE);
    }//GEN-LAST:event_btnObrisiDanActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (noviDan == null) {
        } else {
            try {
                ProgramFormaKontroler.pripremiFormu(pnlPrikazDana, btnDodajDan, this, pnlObrisiDan, daniZaBrisanje);
                System.out.println("Pozvana je metoda formWindowActivated");
                this.setSize(Integer.MAX_VALUE, (Integer.MAX_VALUE - 1));
                this.setSize(Integer.MAX_VALUE, Integer.MAX_VALUE);
                noviDan = null;
                btnDodajDan.setEnabled(true);
            } catch (Exception ex) {
                System.out.println("Došlo je do greške u metodi formWindowActivated klase ProgramForma " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodajDan;
    private javax.swing.JButton btnObrisiDan;
    private javax.swing.JPanel pnlObrisiDan;
    private javax.swing.JPanel pnlPrikazDana;
    // End of variables declaration//GEN-END:variables

    private void pripremiFormu() throws Exception {
        ProgramFormaKontroler.pripremiFormu(pnlPrikazDana, btnDodajDan, this, pnlObrisiDan, daniZaBrisanje);

    }

    public DanProgram getNoviDan() {
        return noviDan;
    }

    public void setNoviDan(DanProgram noviDan) {
        this.noviDan = noviDan;
    }

}
