package festivalaplikacija.zajednicki.transfer;

/**
 *
 * @author Dušan Kalejski dramski pedagog
 */
public enum Operacija {
    LOGIN,
    DRZAVA_ADD,
    DRZAVA_EDIT,
    DRZAVA_UPDATE,
    DRZAVA_DELETE,
    DRZAVA_GET_ALL,
    DRZAVA_FIND_BY_NAME,
    MESTO_ADD,
    MESTO_GET_ALL,
    MESTO_DELETE,
    MESTO_UPDATE,
    MESTO_FIND_BY_QUERY,
    IZVODJAC_GET_ALL,
    IZVODJAC_ADD,
    IZVODJAC_FIND_BY_QUERY,
    IZVODJAC_DELETE,
    IZVODJAC_UPDATE,
    DAN_PROGRAM_ADD,
    DAN_PROGRAM_GET_ALL,
    DAN_PROGRAM_DELETE,
    DAN_PROGRAM_UPDATE,
    DAN_PROGRAM_FIND_BY_QUERY,
    PROGRAM_ADD,
    PROGRAM_GET_ALL,
    PROGRAM_FIND_BY_DAY,
    PROGRAM_UPDATE,
    PROGRAM_DELETE,
    PROGRAM_FIND_BY_QUERY,
    VRSTA_PROGRAMA_GET_ALL,
    VRSTA_PROGRAMA_ADD,
    VRSTA_PROGRAMA_DELETE,
    VRSTA_PROGRAMA_UPDATE,
    VRSTA_PROGRAMA_FIND_BY_QUERY,
    PROSTOR_GET_ALL,
    PROSTOR_FIND_BY_QUERY,
    PROSTOR_GET_BY_ID,
    PROSTOR_ADD,
    PROSTOR_UPDATE,
    PROSTOR_DELETE,
    END
}
